### ISSUE TITLE
Issue with WIFI hotspot

### ISSUE THREAD

**Issue by notorioustubze** [unreality/LGTV-HK#2]
Hello, My device arrived today and I've followed your instructions and from what I can see successfully flashed the ATOM device. The issue I have is I've followed the instructions for putting the device in to AP mode but it doesn't seem to be broadcasting IE i'n not seeing the LG wifi.  Also I have added a picture of how I've connected the DB9 cable to the ATOM device can you confirm this is correct? Thanks in advance!

<img width="1209" alt="Screenshot 2021-09-14 at 16 57 53" src="https://user-images.githubusercontent.com/53260708/133292474-bce2d082-a609-4997-89c6-847527db66c1.png">

**Comment by unreality** [comment]
The cable looks fine, as for the WiFi AP - does the LED turn to the correct colour/blinking frequency?

If the WiFi AP is not visible, you can also configure the device via serial:
* Plug in your m5 atom
* Launch Terminal.app
* run "screen /dev/cu.usbserial-094E0511F3 115200"
* Type ? then press enter and you should see a printout of the available commands
* Once you have finished configuring the device, press control-a then press k, then choose 'y'
* Reset the device and it should connect to the wifi AP you have configured

**Comment by notorioustubze** [comment]
Hi, Thank you for the rapid response! So yeah when I'm pressing the button the device appears to follow what your instructions say but I still don't get any wifi showing. I have just tried the Terminal instructions on first connection of the device and running that command I get the attached picture. If I run the command a second time I get an error saying sorry couldn't find  PTY.
<img width="568" alt="Screenshot 2021-09-14 at 17 22 08" src="https://user-images.githubusercontent.com/53260708/133296516-aff80776-82b6-46a7-9659-990741a890cf.png">
<img width="294" alt="Screenshot 2021-09-14 at 17 24 14" src="https://user-images.githubusercontent.com/53260708/133296523-d69f651d-0103-474c-8f43-4dc420c15736.png">

**Comment by unreality** [comment]
That image looks like the baud rate is incorrect. Unfortunately I dont have my MacBook available to debug why those commands dont work correctly on OSX. I'll have to look into it tomorrow.

If you want to take a crack at solving the issue, another possibility is to download the Arduino IDE and use the serial monitor included in that to try different baud rates, if you work your way up from 9600 (just press the reset button after each attempt to try a new baud rate) you should eventually find the correct baud rate which will print out the console correctly. Im unsure why it is not working on 115200 since thats the default I set when compiling.

Im also unsure why the WiFI AP is not showing up, i'll see if i can replicate that tomorrow as well.

**Comment by notorioustubze** [comment]
Hi, no problem I have downloaded Arduino but I'm unsure where to put the different baud rates. If I click serial monitor in the top right I get the error "board at null is unavailable".

**Comment by notorioustubze** [comment]
Hi Unreality, great news I was able to configure the device using Arduino IDE and have successfully joined the device to my wifi and set  it up in HK. Only Issue I have now is it's not controlling my TV. Is it possible the cable is wired up incorrectly? Thanks in advance!

**Comment by unreality** [comment]
That's great news, you can try flipping the RX/TX wires if the m5 is not communicating correctly with the TV (eg on your cable red->R, blue->T), also confirm the ground is connected to the right pin - https://www.lg.com/us/business/download/resources/BT00001837/UV340C-U_Install_Manual_170825.pdf (pg27) gives a pinout for the rs232 connector.

**Comment by notorioustubze** [comment]
One other thing my device has a solid yellow light now despite being connected to HK I notice your instructions state it should be solid green for successful connection to HK?

**Comment by unreality** [comment]
Looking at the code, it looks like it wont ever make the LED green, i'll have to add a fix for it

**Comment by notorioustubze** [comment]
I've tried changing the cable around but still no joy I'm afraid. I've noticed in HK if I switch the state to off it appears off for a second or two and then reverts to on. Unsure if that's any help to you?

**Comment by unreality** [comment]
One other thing to check is that your TV has a 'SET ID' of 01, your manual should show how to set the ID of the TV.

**Comment by notorioustubze** [comment]
Just checked the ID and can confirm it's set to 01.

**Comment by unreality** [comment]
I'll reflash a device and see if I can replicate the issue on my set here

**Comment by notorioustubze** [comment]
Perfect! Thank you for your help.

**Comment by unreality** [comment]
I've added a new release which might fix your issues, the firmware was never reporting anything other than 'on' which may have been conflicting with your actions. The new release will also turn green when everything is set up correctly.

If you choose not to 'erase flash' when using NodeMCU Flasher, it should keep your existing pairing data as well

**Comment by notorioustubze** [comment]
Hi, So I've reflashed the device and can confirm that it now shows green and it's behaviour in HK is corrected IE, off stays off and on stays on. Unfortunately I'm still not able to control the TV. I've tried reverting the cable back to the original layout from my first post too and no Joy.

**Comment by notorioustubze** [comment]
Would it make a difference if the cable I used was DB9 male to female?

**Comment by unreality** [comment]
It shouldn't make a difference - the only thing that will matter is that the RX/TX pins are connected to the right ports on the plug., and the m/f cables will flip them (so flipping the RX/TX lines like you tried should work) You may want to go through your tv's manual and make sure there isn't a setting which turns on the rs232 port - i saw a mention in a few places that it needs to be enabled in settings on some tvs.

If you have some dupont wires lying around you could splice into the rs232 port manually to confirm you are wired into the right pins.

**Comment by notorioustubze** [comment]
Hi Unreality, I tested my cable at work today using a continuity tester a low and behold I was using the completely wrong wires to connect to the Atom. After correctly re-wiring the device it now works perfectly and I could not be happier! I've been wanting to make this TV "Smart" for a long time and what you've created works exceptionally well so thank you for your support!
