### ISSUE TITLE
Volume Bar Bug

### ISSUE THREAD

**Issue by notorioustubze** [unreality/LGTV-HK#3]
Hi, sorry me again… So while the TV is on the volume bar keeps flashing up on the screen as if the volume is being controlled however the volume remains the same. 

Also some feature requests:
1)would it be possible to add other options to the selector such as a live tv (to flick back from HDMI input) or a guide option?
2)Is it possible to expose volume control in HK as a light bulb so Volume can be adjusted with a slider?
3) Do you think OTA updates could ever be enabled to keep the device on the latest version?

Thanks in advance!

**Comment by unreality** [comment]
Sounds like the tv is displaying the volume bar every time the atom is polling the tv to find the current volume (does it appear every second? - thats the default polling interval). The polling could be disabled, but then you would lose the ability to have a correct volume inside homekit (ie if someone changes the volume with the remote, homekit wont be aware of the new volume)

Maybe there is a tv setting that will disable the volume displaying? What model is your tv?

All the other stuff can probably be done, its just a matter of motivation. The volume slider is the most work - but its reasonably easy to do.

**Comment by notorioustubze** [comment]
I've taken a look through the manual but I couldn't find anywhere it suggests being able to turn off the volume slider, but you may have more luck. I have a LG 42LH2000 and yeah it pulses every second. Thanks in advance!

**Comment by notorioustubze** [comment]
Hi, sorry to chase if the other features require to much time and effort then I’m perfectly fine with the device provided the function as it does now. Are you able to remove the volume polling though as I can’t use the tv with it constantly popping up? Thanks in advance.

**Comment by unreality** [comment]
I found what could be a fix for the volume bar showing but I havent had time to test it yet. I'll try upload a test release this week.

**Comment by notorioustubze** [comment]
Fantastic! I’ll wait out and thanks again.

**Comment by notorioustubze** [comment]
@unreality any joy with the fix for this? Thanks in advance!

**Comment by unreality** [comment]
I just tested a build which turns off the OSD, unfortunately it turns off the OSD for the entire tv, so feedback from remotes etc shows no UI. I can upload this version, but i suspect you wouldnt want the OSD disabled completely.

**Comment by notorioustubze** [comment]
@unreality although not ideal I think at least the TV will be able to be used while the device is plugged in. So if you wouldn’t mind releasing this version until something else is discovered I’d be most great full. Thanks again

**Comment by notorioustubze** [comment]
@unreality hey sorry to chase but do you have any update on this? Thanks in advance!

**Comment by unreality** [comment]
Sorry, i've about exhausted all my knowledge on this one. I'm not sure how to get it to work without the volume bar appearing. Turning off the OSD might work, but it essentially makes the TV uncontrollable via any means except HomeKit (even if you turn the OSD back on with the remote, the atom will turn it off again within a second)

If I get some time I might make a configurable option to disable volume polling, but ive mostly moved onto other projects at the moment, and unfortunately, the current build works for my old LG :/

**Comment by notorioustubze** [comment]
@unreality No worries thank you for your time and effort.

**Comment by notorioustubze** [comment]
@unreality Hi Unreality, I reached out on Reddit to see if there was one that could assist with my volume bug issue. Anyway someone has commented back "If you comment out the IF at line 155 ‘in main.ccp’, does it still happen?" I've tried my best to manually change this myself, I've downloaded Visual Studio Code, I've installed the PlatformIO plugin, I've cloned the repository but I have no idea what I'm doing once I've got the code up so I was hoping you might be able to try what they said and upload a revision so that I can try it out? Appreciate you've moved on from the Project however I'm stuck with a device I can't use at the min so I'd really like to get it working. Thanks in advance!

**Comment by unreality** [comment]
@notorioustubze its more likely to be the block at line 203 (https://github.com/unreality/LGTV-HK/blob/f91bd5d35dc70cbdb80397cc09bfbf02b3619157/src/main.cpp#L203), line 155 controls applying an update from HomeKit (eg when you change the volume on your iPhone) -- so a volume update appearing on the screen would be acceptable (or even wanted)

I created a new release https://github.com/unreality/LGTV-HK/releases/tag/v0.2-no-volume-controls which is completely untested (ive just removed the television speaker accessory) - it might help with the volume bar appearing, but you will only be able to control power and switch between inputs.

**Comment by notorioustubze** [comment]
@unreality Resolved the issue and now works perfectly thank you for the additional effort it's really appreciated. Wish you the best.
